blank_issues_enabled: false
contact_links:
  - name: Group
    url: https://t.me/QAuxiliaryChat
    about: Our Telegram Group 
  - name: smart-question
    url: https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
    about: READ BEFORE YOU ASKING ANY QUESTION
